# Generated by Django 4.2.5 on 2023-10-18 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item", old_name="item_price", new_name="item_pricey",
        ),
    ]
